channels:
  - nvidia
  - pytorch
  - nvidia/label/cuda-12.1.0
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - cuda
  - torchvision 
  - torchaudio 
  - pytorch-cuda=12.1
  - numba
  - jupyter
  - matplotlib
  - pip:
      - ninja

